// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acoustic_transmission.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AcousticTransmission {
  public static partial class Acoustics
  {
    static readonly string __ServiceName = "acoustic_transmission.Acoustics";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::AcousticTransmission.CommandRequest> __Marshaller_acoustic_transmission_CommandRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AcousticTransmission.CommandRequest.Parser));
    static readonly grpc::Marshaller<global::AcousticTransmission.AcousticResponse> __Marshaller_acoustic_transmission_AcousticResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AcousticTransmission.AcousticResponse.Parser));
    static readonly grpc::Marshaller<global::AcousticTransmission.AcousticPayload> __Marshaller_acoustic_transmission_AcousticPayload = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AcousticTransmission.AcousticPayload.Parser));

    static readonly grpc::Method<global::AcousticTransmission.CommandRequest, global::AcousticTransmission.AcousticResponse> __Method_GetAcousticRequest = new grpc::Method<global::AcousticTransmission.CommandRequest, global::AcousticTransmission.AcousticResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAcousticRequest",
        __Marshaller_acoustic_transmission_CommandRequest,
        __Marshaller_acoustic_transmission_AcousticResponse);

    static readonly grpc::Method<global::AcousticTransmission.AcousticPayload, global::AcousticTransmission.AcousticResponse> __Method_ReturnAcousticPayload = new grpc::Method<global::AcousticTransmission.AcousticPayload, global::AcousticTransmission.AcousticResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ReturnAcousticPayload",
        __Marshaller_acoustic_transmission_AcousticPayload,
        __Marshaller_acoustic_transmission_AcousticResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AcousticTransmission.AcousticTransmissionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Acoustics</summary>
    [grpc::BindServiceMethod(typeof(Acoustics), "BindService")]
    public abstract partial class AcousticsBase
    {
      public virtual global::System.Threading.Tasks.Task GetAcousticRequest(global::AcousticTransmission.CommandRequest request, grpc::IServerStreamWriter<global::AcousticTransmission.AcousticResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ReturnAcousticPayload(global::AcousticTransmission.AcousticPayload request, grpc::IServerStreamWriter<global::AcousticTransmission.AcousticResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Acoustics</summary>
    public partial class AcousticsClient : grpc::ClientBase<AcousticsClient>
    {
      /// <summary>Creates a new client for Acoustics</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AcousticsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Acoustics that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AcousticsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AcousticsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AcousticsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::AcousticTransmission.AcousticResponse> GetAcousticRequest(global::AcousticTransmission.CommandRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAcousticRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AcousticTransmission.AcousticResponse> GetAcousticRequest(global::AcousticTransmission.CommandRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAcousticRequest, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::AcousticTransmission.AcousticResponse> ReturnAcousticPayload(global::AcousticTransmission.AcousticPayload request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReturnAcousticPayload(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::AcousticTransmission.AcousticResponse> ReturnAcousticPayload(global::AcousticTransmission.AcousticPayload request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ReturnAcousticPayload, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AcousticsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AcousticsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AcousticsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAcousticRequest, serviceImpl.GetAcousticRequest)
          .AddMethod(__Method_ReturnAcousticPayload, serviceImpl.ReturnAcousticPayload).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AcousticsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAcousticRequest, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AcousticTransmission.CommandRequest, global::AcousticTransmission.AcousticResponse>(serviceImpl.GetAcousticRequest));
      serviceBinder.AddMethod(__Method_ReturnAcousticPayload, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::AcousticTransmission.AcousticPayload, global::AcousticTransmission.AcousticResponse>(serviceImpl.ReturnAcousticPayload));
    }

  }
}
#endregion
