name: NightlyPackageCreator
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive
      - name: Checkout submodule
        run: |
          git submodule update --force --recursive --init
      - name: Copy assets directory
        run: |
          mv Assets ../       
          mv .gitignore .gitmodules .gitattributes ../Assets
      - uses: actions/checkout@v2
        with:
          ref: package-nightly
      - name: Prepare Github
        run: |
            git config --global user.name 'Automation'
            git config --global user.email 'generator@github.action'
      - name: Remove current assets and copy new
        run: |
          rm -r *
          mv ../Assets/* .
          git add *
          if [[ -n $(git status -s) ]] 
          then
            echo "Files have changed in this revision."
            git commit -am "Asset package based on revision $(git rev-parse --short "$GITHUB_SHA")."
            git push
          else
            echo "Files did not change in this revision."
          fi
